apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp1
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: rsvp1
    spec:
      containers:
      - name: rsvp-app1
        image: teamcloudyuga/rsvpapp
        ports:
        - containerPort: 5000
          name: web-port
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: TEXT1
          valueFrom:
            configMapKeyRef:
              name: customer2
              key: TEXT1
        - name: TEXT2
          valueFrom:
            configMapKeyRef:
              name: customer2
              key: TEXT2
        - name: COMPANY
          valueFrom:
            configMapKeyRef:
              name: customer2
              key: COMPANY